# See https://prek.j178.dev/ for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version.python = "python3.13"

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
	{ id = "check-added-large-files", args = [
		"--maxkb=500",
	] },
	{ id = "check-case-conflict" },
	{ id = "check-illegal-windows-names" },
	{ id = "check-json" },
	{ id = "check-merge-conflict" },
	{ id = "check-symlinks" },
	{ id = "check-toml" },
	{ id = "check-vcs-permalinks" },
	{ id = "check-yaml" },
	{ id = "destroyed-symlinks" },
	{ id = "detect-private-key" },
	{ id = "end-of-file-fixer" },
	{ id = "fix-byte-order-marker" },
	{ id = "forbid-submodules" },
	{ id = "mixed-line-ending", args = [
		"--fix=lf",
	] },
	{ id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/ComPWA/taplo-pre-commit"
rev = "v0.9.3"
hooks = [{ id = "taplo-format" }]

[[repos]]
repo = "https://github.com/rvben/rumdl-pre-commit"
rev = "v0.1.35"
hooks = [{ id = "rumdl-fmt" }]
